### ISSUE TITLE
Release a binary on github

### ISSUE THREAD

**Issue by m040601** [cgxeiji/scholar#1]
Thanky for your work on this promising tool.
Any chance you could actualy release it as a binary on github ?

Releasing a binary, just makes your tool available for someone who just wants to check it out quickly, compare it with others.

Not everyone has the entire go distribution installed or as a simple user is familiar with compiling.Besides that releasing a binary, would make it easier for others to create a package for a Linux distro, based on the binary (ex. Ubuntu,  Archlinux AUR).i

Do you know this tool, https://github.com/goreleaser/goreleaser ?

https://help.github.com/en/articles/creating-releases
you can also use:

travis, https://blog.questionable.services/article/build-go-binaries-travis-ci-github/
circleci, https://circleci.com/blog/publishing-to-github-releases-via-circleci/

**Comment by cgxeiji** [comment]
Hi, thank you for your suggestion!

You are definitely right, I will check about releasing the pre-compiled binaries.

**Comment by cgxeiji** [comment]
a005071 should close this issue.

Thank you for your feedback!
