### ISSUE TITLE
nice tool!  question

### ISSUE THREAD

**Issue by rhaynes74** [cgxeiji/scholar#4]
Many thanks for developing this, I will install and play around.      A couple of quick questions:

i) can I have multiple projects?
ii) can I link to a file instead of just adding a file?
iii) can I add note files to a project? 
iv) how about note files attached to a file?
v) restrictions on file types in libraries?

**Comment by cgxeiji** [comment]
Thank you for your kind words!

The answers are:
i) yes, you can pass the `--library`/`-l` flag with the name of the library. You can configure the location of each library in the configuration file (usually at `$HOME/.config/scholar/scholar.yaml`)
ii) I plan to add this feature in the future.
iii) You can add notes inside the `yaml` file attached to the entry. (Although this might change in the future)
iv) Attaching multiple files will be a future feature.
v) For now, as long as you can copy/paste the file, you can attach any type of reference (images, 3D models, executables, etc.)

I hope these answer your questions!
